allprojects {
    repositories {
        google()
        mavenCentral()
    }

    // Injeta a propriedade 'flutter' globalmente para todos os plugins de áudio
    ext.flutter = [
        compileSdkVersion: 34,
        minSdkVersion: 24,
        targetSdkVersion: 34
    ]
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    ext.flutter = rootProject.ext.flutter
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
